### ISSUE TITLE
Changing uuid value every time a post is saved

### ISSUE THREAD

**Issue by aesmail** [areski/ex-chitchat#1]
Please disregard this issue if I'm misunderstanding your intent.

If you don't want the UUID to change every time you update a post, you might want to use `get_field/2` instead of `get_change/2` [here](https://github.com/areski/ex-chitchat/blob/642add1a5c8096762e24f55ec7d9be584b188374/lib/chit_chat/blog/post.ex#L24).

**Comment by areski** [comment]
Thanks for that :)
